[package]
name = "wasm"
version = "0.1.0"
authors = ["iMasanari <14dd023@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
wasm-bindgen = { version = "^0.2", features = ["serde-serialize"] }

[lib]
crate-type = ["cdylib"]
path = "./src/wasm/lib.rs"
